/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tacos;

import javax.swing.JOptionPane;

/**
 *
 * @author chumo
 */
public class Inico extends javax.swing.JFrame {

    /**
     * Creates new form Inico
     */
    public Inico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        lbl1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Iniciar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl1)))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(lbl1)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int p4=JOptionPane.showConfirmDialog(this, "Te ama?", "Pregunta v", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        int p5=JOptionPane.showConfirmDialog(this, "Te manda mensajes?", "Pregunta x", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        int p6=JOptionPane.showConfirmDialog(this, "Te ha ayudado en algo?", "Pregunta u", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        int p1= JOptionPane.showConfirmDialog(this, "Tiene queso?", "Pregunta 1", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        int p2= JOptionPane.showConfirmDialog(this, "Tiene carne?","Pregunta 2",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        int p3= JOptionPane.showConfirmDialog(this,"La tortilla es de maiz?","Pregunta 3",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(p1==JOptionPane.YES_OPTION && p2==JOptionPane.YES_OPTION && p3==JOptionPane.YES_OPTION){
            lbl1.setText("En base a la informacion obtenida determinamos que el taco que estas comiendo es una quesadilla");
            
            
        }
        if(p1==JOptionPane.YES_OPTION && p2==JOptionPane.YES_OPTION && p3==JOptionPane.NO_OPTION){
          lbl1.setText("En base a la informacion obtenida hemos determinado que es una campechana");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lbl1;
    // End of variables declaration//GEN-END:variables
}
